notL2p4THXlW6JWbpRDdBzt8Xiq1SjIhtBJ9ZajX4otL2p4THXlW6JWbpRDdBzt8Xiq1SjIhtBJ9ZajX4otL2p4THXlW6JWbpRDdBzt8Xiq1SjIhtBJ9ZajX4ame: Release Please
on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write
jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.batoaqaa }}
          release-type: simple
